In [1]:
import numpy as n

In [2]:
a=n.array([1,2,3,4])  #creating rank 1 array
print(type(a))

<class 'numpy.ndarray'>


In [3]:
print(a.shape)

(4,)


In [6]:
print (a[0])

1


In [8]:
b=n.array([[1,2,3],[4,5,6]])  #creating rank 2 array
print(b.shape)

(2, 3)


In [10]:
a = n.zeros((2,2))#create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [14]:
b = n.ones((2,2))#create an array of all ones
print(b)

[[1. 1.]
 [1. 1.]]


In [13]:
c= n.full((2,2),7)#creating a constt array
print(c)

[[7 7]
 [7 7]]


In [15]:
d= n.eye(2) #create a 2*2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [17]:
e= n.random.random((2,2)) #create an array of random values
print(e)

[[0.8777856  0.85499719]
 [0.07265007 0.56978563]]


In [18]:
n.arange(10) #create array with increamental values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
n.arange(2,4,0.7)

array([2. , 2.7, 3.4])

In [22]:
n.arange(2,10,dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
n.linspace(1.,4.,6)#crating array with specifed no of elements
                   #spaces between beginning and end values equally

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [27]:
a=n.indices((3,5)) #creating a set of arrays
b=n.indices((3,3))
print(a)
print(b)

[[[0 0 0 0 0]
  [1 1 1 1 1]
  [2 2 2 2 2]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]
[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [30]:
#array indexing
a=n.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])#creating a 2d array of (3,4) 
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
#slicing containg first 2 rows and columns 1 and 2
b=a[:2,1:3]
print(b)
#slicing containg first 3 rows and columns 1,2 and 3
c=a[:3,0:3]
print(c)
d=a[1:4,2:4]
print(d)

[[2 3]
 [6 7]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[ 7  8]
 [11 12]]


In [43]:
print(a[0,1])  #modifying data
b[0,0]=12
print(b[0,0])

12


In [41]:
print(a[1,:])

[5 6 7 8]


In [44]:
a=n.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])#creating a 2d array of (3,4) 
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [49]:
row_r1=a[1,:]
print(row_r1,row_r1.shape)#printing row with its shape

[5 6 7 8] (4,)


In [50]:
row_r2=a[1:2,:]
print(row_r2,row_r2.shape)

[[5 6 7 8]] (1, 4)


In [53]:
col_c1=print(a[:,0])

[1 5 9]


In [54]:
a=n.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])#creating a 2d array of (4,3) 
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [65]:
b=n.array([0,1,0,1])


In [71]:
print(a[n.arange(4),b])

[31 25 37 41]


In [70]:
a[n.arange(4),b] +=20 #added 10,20,20 than subtracted 20.....
print(a)

[[31  2  3]
 [ 4 25 16]
 [37  8  9]
 [10 41 12]]


In [72]:
#boolean array indexing
a=n.array([[1,2],[3,4],[5,6]])
print(a)


[[1 2]
 [3 4]
 [5 6]]


In [78]:
bool_idx=(a>2)
print(bool_idx)
print(a[bool_idx])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [77]:
bool_idx=(a==2)
print(bool_idx)

[[False  True]
 [False False]
 [False False]]


In [79]:
#datattypes
a=n.array([[1,2],[3,4],[5,6]])
print(a)


[[1 2]
 [3 4]
 [5 6]]


In [80]:
print(a.dtype)

int32


In [83]:
a=n.array([1.0,2.1])
print(a.dtype)

float64


In [84]:
a=n.array([[1,2],[3,4],[5,6]],dtype=n.int64)
print(a.dtype)

int64


In [88]:
#array maths
a=n.array([1.0,2.1],dtype=n.float64)
b=n.array([1.0,3.1],dtype=n.float64)

In [89]:
print(a+b)
print(n.add(a,b))

[2.  5.2]
[2.  5.2]


In [94]:
print(a-b)
print(n.subtract(a,b))

[ 0. -1.]
[ 0. -1.]


In [92]:
print(a*b)#element wise multiplication

[1.   6.51]


In [93]:
print(a/b)

[1.         0.67741935]


In [96]:
print(a)
print(n.sqrt(a))

[1.  2.1]
[1.         1.44913767]


In [97]:
a=n.array([[1,2],[3,4]])
b=n.array([[5,6],[7,8]])


In [99]:
v=n.array([9,10])
u=n.array([11,12])

In [100]:
print(v.dot(u))#matrix mul

219


In [107]:
print(a)
print(v)
print(v.dot(a))

[[1 2]
 [3 4]]
[ 9 10]
[39 58]


In [104]:
print(a)
print(b)
print(a.dot(b))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [110]:
#sum function
a=n.array([[1,2],[3,4]])
print(n.sum(a))#sum of all elements
print(a)
print(n.sum(a,axis=0))#column 
print(n.sum(a,axis=1))#row

10
[[1 2]
 [3 4]]
[4 6]
[3 7]


In [111]:
print(a)


[[1 2]
 [3 4]]


In [113]:
print(a.T)#transpose

[[1 3]
 [2 4]]


In [114]:
#broadcasting

In [118]:
a=n.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=n.empty_like(a) #creating an empty matrix with same shape as a
v=n.array([1,0,1])

print(a)
print(b)
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]


In [122]:
for i in range(4):
    b[1,:] = a[1,:]+v  

In [124]:
print(b)

[[ 1  2  3]
 [ 5  5  7]
 [ 7  8  9]
 [10 11 12]]


In [125]:
a=n.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=n.array([1,0,1])
b=a+v
print(b)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [128]:
#reshaping
v=n.array([1,2,3])
w=n.array([4,5])
print(v)

[1 2 3]


In [127]:
print(n.reshape(v,(3,1)))#changing row in column

[[1]
 [2]
 [3]]


In [129]:
print(n.reshape(v,(3,1))*w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [130]:
print(n.reshape(v,(3)))#remains row only

[1 2 3]
